# Render configuration for Docker-based deployment
services:
  - type: web
    name: rsa-signature-app
    env: docker
    plan: free

    # Git repo and branch to deploy (replace with your own)
    repo: https://github.com/<your-username>/rsa-sign
    branch: main

    # Path to Dockerfile (relative to repo root)
    dockerfilePath: Dockerfile

    # Build and start commands
    buildCommand: |
      # build frontend
      cd Front_Rsa/Rsa_web && npm ci && npm run build
    startCommand: |
      # start .NET backend (serves both API and static files)
      dotnet RsaSignApi.dll

    # Environment variables
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000

    # Health check
    healthCheckPath: /
